import Head from "next/head"
import { useSelector } from "react-redux";
import axios from "axios";

import { GlobalStyle } from "../globalStyles";
import FormModal from "../components/FormModal";
import Question from "../components/Question";


export default function Home({ questions }) {

  const playerInfo = useSelector((state) => state);

  return <>
    <Head>
      <title>Quiz Game</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <GlobalStyle />
    <main style={{display: "flex", justifyContent: "center", alignItems: "center", height: "100vh", width: "100vw"}}>
      <FormModal />
      {playerInfo.name  && (<Question data={questions} />)}
    </main>
  </>;
};

export async function getServerSideProps(context){

  const response = await fetch("https://opentdb.com/api.php?amount=10&type=multiple")
  const questions = await response.json();

  return {
    props: {
      questions
    },
  };
};
